### ISSUE TITLE
UnrecognizedPropertyException

### ISSUE THREAD

**Issue by spikalo** [maseev/alpaca-trade-api-java#8]
Hi,
When I want to get account info I get a com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.
What am I doing wrong?

**Comment by maseev** [comment]
The server API has changed since the last time I checked the client compatibility. Consider using the following [guide](https://alpaca.markets/learn/generating-alpaca-api-client-in-3-easy-steps-with-the-openapi-generator/) to generate the client library from the OpenAPI specification Alpaca provides.
